/** Viewer-owned copy of the Workbench uploader display names. */
export const WORKBENCH_UPLOADER_NAMES: Record<string, string> = {
  Vertax: "杨信诚",
  xensedyl: "董耀琳",
  P0lar1z: "魏来",
  zhangdaohu: "张道虎",
  xueyuquan: "薛毓铨",
  fza1796262052: "方占奥",
  SkyhaoLi: "李天浩",
  WBH333: "王宝合",
  dctx: "白伟杰",
  etince11e: "姜毅峰",
  hubobi: "胡博",
  xijingfeng: "徐小平",
  lxy0407: "罗霄羽",
  bdjahxs: "任佳林",
  yhsguejh: "莫凡",
  shilin5499: "祝石林",
  yangbaicai147: "杨蔡田雨",
  QiuDekang: "邱德康",
  "XR-Bot0": "邬思彤",
  "XR-Bot1": "邬思彤",
  "XR-Bot3": "洪锐",
  "XR-Bot4": "洪锐",
};
